### ISSUE TITLE
whitespace after quoted strings leads to terminator errors

### ISSUE THREAD

**Issue by Shishqa** [KmolYuan/yaml-peg-rs#14]
When parsing

```yaml
fit:
- 'b'          
sub:
- title: Lay with Images
```

(mind the whitespace after `'b'`)

the parser gives an error:

```
test tests::test_yaml ... FAILED

failures:

---- tests::test_yaml stdout ----
thread 'tests::test_yaml' panicked at src/tests/mod.rs:4:5:
invalid sequence terminator:

85:6
- 'b'
     ^
```

The same with maps:

![image](https://github.com/user-attachments/assets/2a7597a6-989d-4145-aae9-f9f668a95e53)
