### ISSUE TITLE
invalid map terminator \n\n for maps

### ISSUE THREAD

**Issue by joshuataylor** [KmolYuan/yaml-peg-rs#6]
I'm trying to parse a yaml file that [dbt](https://github.com/dbt-labs/dbt-core) uses, which looks like this:
```
version: 2
models:
    - name: orders
      columns:
          - name: c_custkey
            tests:
                - not_null
```

However, I'm getting this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "invalid map terminator: \n\n(4:14)\n      columns:\n~~~~~~~~~~~~~^"', src/dbt_parse.rs:98:34
```

Reproduction:
```
    let f = "version: 2
models:
    - name: orders
      columns:
          - name: c_custkey
            tests:
                - not_null";
    let (n, anchors) = parse(&f).unwrap();
```
