### ISSUE TITLE
Read comment

### ISSUE THREAD

**Issue by guiyomh** [KmolYuan/yaml-peg-rs#8]
Hi, very good job for your lib. 
Is it possible to read the comments? I explain:

I want to write a generator of documentation for a collection of YAML files. All the file has some comments like this:

```yaml
# list all the variables
# multiline comment
# bla blabla...
variables:
   # name of the docker images
   IMAGE_NAME: my-image
   # tag applied on the images
   IMAGE_TAG: latest 
```
I want access to the comment for example with the node `IMAGE_NAME`, I would like to have something like: `node.comment() `. Is it possible with your lib, and how?
