### ISSUE TITLE
Known issue: Empty values (null) in maps cause wrong indent level

### ISSUE THREAD

**Issue by KmolYuan** [KmolYuan/yaml-peg-rs#9]
```yaml
a:
  b:
c:
```

will be parsed as

```yaml
a:
  b:
    c:
```

Use this instead

```yaml
a:
  b: ~
c: ~
```
